source/objects/responseClass.m
See Issue: https://github.com/WEC-Sim/WEC-Sim/issues/83
This is what I had implemented to fix the ```filesep filesep``` issue. But @cmichelen, I think commit a0fe9b3ba07bed272692079364d89d2dfd3bac09 may have already fixed this issue, as long as all fileseps are also stripped from the body name in BEMIO.
Just today I synced my local branch with the latest updates, and I was able to run paraview with the RM3 case - which didn't previously work before commit a0fe9b3ba07bed272692079364d89d2dfd3bac09.
=> Fix Issue #83, pt 3 - Paraview filesep

source/functions/wecSimMCR.m, source/objects/bodyClass.m, source/wecSim.m
Speed improvement for MCR:
* hydroData is stored in memory between uses to eliminate redundant h5 file read operations.
* Significantly improves overall MCR runtime when each case has a short runtime.
* if h5File is changed between runs, then hydroData is always reloaded from h5 file.
I have two test cases I can provide if requested.
See Issue https://github.com/WEC-Sim/WEC-Sim/issues/145 
@kmruehl
=> Store hydroData between runs for MCR - Improved MCR runtime

source/objects/responseClass.m
when reading moorDyn results, "Lines.out" is not closed.
=> add missing fclose() to responseClass

source/objects/waveClass.m
This PR does three things:
1. Converts the property help for all properties into the Matlab multi-line format, for example, property help for 'viz' now returns:
```
>> help waveClass.viz
viz - Structure defining visualization options
Should be a structure containing the fields 'numPointsX' and
'numPointsY'. numPointsX is the number of visualization points
in x direction, and numPointsY the number of visualization points
in y direction
```
2. Adds help for the waveClass constructor, in the standard matlab help format, so now you can do:
```
>> help waveClass.waveClass
waveClass constructor
Syntax
obj = waveClass (type)
Input
type - string containing the type of wave simulation to be
generated, the possible values are
'noWave' : no waves
'noWaveCIC' : No waves but with the Convolution …
```
=> Improving help, and splitting out wave elevation calc to separate method

source/objects/responseClass.m
When reading moorDyn outputs, each "LineX.out" file, the file is left open when reading. This can cause matlab to crash when repeatedly running models with moorDyn
=> Update responseClass.m - Add missing fclose(fid)

source/functions/BEMIO/Combine_BEM.m, source/functions/BEMIO/Excitation_IRF.m, source/functions/BEMIO/Plot_BEMIO.m, source/functions/BEMIO/Radiation_IRF.m, source/functions/BEMIO/Radiation_IRF_SS.m, source/functions/BEMIO/Read_AQWA.m, source/functions/BEMIO/Read_NEMOH.m, source/functions/BEMIO/Read_WAMIT.m, source/objects/responseClass.m, source/objects/simulationClass.m, source/objects/waveClass.m, tutorials/OSWEC/hydroData/README.md, tutorials/OSWEC/hydroData/README.txt, tutorials/RM3/hydroData/README.md, tutorials/RM3/hydroData/README.txt
Redirect old files from WEC-Sim\tutorials\BEMIO to WEC-Sim\examples\BEMIO
Fixed some small typos
=> Redirect to \examples\BEMIO\ and small typos

source/functions/paraViewVisualization.m, source/objects/waveClass.m
create folder before creating 'bodies.txt' file  to avoid "No such file or directory" on fopen() call on windows
use correct arity when calling waveElevationGrid()
=> bugfixes for paraview

source/objects/simulationClass.m, source/wecSim.m
Added a `simulationClass` property flag that saves the WEC-Sim output object to a structure, e.g. `output = struct(output);`. This is necessary for use by MHKiT (and python in general), as demonstrated by the [MHKiT WEC-Sim Example](https://mhkit-software.github.io/MHKiT/wecsim_example.html). This is feature is initialized in the `wecSimInputFile.m` by specifying `simu.outputStructure = 1;`
**NOTE: I requested a merge with master as this is needed by MHKiT now** @ssolson and @rpauly18
=> WEC-Sim output to a MATLAB structure

docs/man/webinars.rst
This commit switches from using the :download: directive to static links for the webinar slides files (in docs/man/webinars.rst). The value of this changes is that the link paths will not be recalculated every time that the docs are built and only a single copy of the files is stored (per branch).
=> Prefer Static Links to Download Directive in Sphinx Docs

source/functions/paraViewVisualization.m, source/functions/postProcess.m, source/objects/bodyClass.m, source/objects/mooringClass.m, source/objects/responseClass.m, source/objects/waveClass.m, source/wecSim.m
This PR fixes issue #468. A previous PR (#428) changed how the pressure outputs for paraview (hspressure, wpressurenl, wpressurel) are passed in postProcess and paraViewVisualization. The references to these three pressures are now consistent.
All continuous integration tests pass. I confirmed that the Paraview application outputs correctly for every possible combination of     
simu.nlHydro, simu.pressureDis , and simu.paraview
=> Paraview pressure fix

source/functions/paraViewVisualization.m, source/objects/responseClass.m
This PR fixes a bug with the simMechanics file name in paraview output. The simMechanics file was previously changed to include the path for compatibility with WEC-Sim PCT. Paraview output requires just the file name to define the CASE.pvd file. This is resolved by this PR.
.pvd and .pvsm files can be opened successfully with Paraview now.
=> Paraview bug with simMechanics file name

docs/man/api.rst, source/objects/waveClass.m
This commit removes an autodoc call and a reference in another method to the removed `write_paraview_vtp` method of `waveClass`. This allows the dev branch docs to build again.
=> Remove reference to removed method to repair dev docs

source/objects/bodyClass.m, source/wecSim.m
This PR resolves #497 by setting cb=cg if it's not defined and adding a warning. This is true for both non-hydro bodies and drag bodies. 
@nathanmtom please test with a non-hydro body case (e.g. WECCCOMP) by commenting out body.cb in the input file. 
@dforbush2 please test by a drag by case by commenting out body.cb in the input file. 
You should get a warning that says something like
```matlab
Warning: Non-hydro body(2) center of buoyancy (cb) set equal to center of gravity (cg), [0 0 -10.9] 
> In wecSim (line 196) 
```
=> Resolving #497 bug with body.cb

examples/BEMIO/CAPYTAINE/Coer_Comp/coer_comp.py, examples/BEMIO/CAPYTAINE/Cubes/cubes.py, examples/BEMIO/CAPYTAINE/Cylinder/cylinder.py, examples/BEMIO/CAPYTAINE/Ellipsoid/ellipsoid.py, examples/BEMIO/CAPYTAINE/OSWEC/oswec.py, examples/BEMIO/CAPYTAINE/RM3/rm3.py, examples/BEMIO/CAPYTAINE/Sphere/sphere.py, examples/BEMIO/CAPYTAINE/run_cases.py
Fixes a line in the Capytaine case files (sphere.py, ellipsoid.py, etc) that imported the call_capytaine.py file using an absolute path. This changes those lines to import the function using a relative path that should work for all users.
=> add relative path in capytaine cases

source/objects/simulationClass.m, source/wecSim.m
Instead of moving the plotting scripts outside of the `responseClass`, a solution that would require us to revise all working cases, I opted to keep the output object called `output`, but also save an output structure called `outputStructure`. Open to feedback.
=> resolving #514

source/functions/BEMIO/Normalize.m
This PR resolves issue #601. There is a small bug that only occurs when non-WAMIT codes are used in the Combine_BEM() BEMIO function. 
The initialization of hydro.Ainf is added into Normalize.m for all non-WAMIT codes, so that they can be properly concatenated in the Combine_BEM function. I added an inline comment stating that the initial value (added mass at the highest frequency given) is overwritten by more accurate method in radiation_IRF.m
=> Fix Combine_BEM Ainf initialization

source/wecSimStartup.m
I was reinstalling WEC-Sim on a new operating system and I remembered that one of the annoying aspects of using the `startup.m` file was the temporary variable `wecSimPath` being placed into the global workspace. 
I don't believe this variable is needed in any other situation, so my preference is to clear it from the workspace, which this PR does automatically.
=> Clear temporary variable added in startup.m

docs/_include/viz.rst, source/functions/paraview/pressureGlyphs.py
Update the ParaView _pressureGlyphs.py_ macro for the latest ParaView version (5.9.1). The issue was that the current version of ParaView is not backwards compatible. 
@kmruehl To Do:
-  [x] Mention the supported ParaView version somewhere in the Documentation or website.
=> Fixes #459. Update ParaView macros for Paraview 5.9

source/functions/BEMIO/Write_H5.m
Fix a bug for BEMIO when reading the mean drift force. 
Note that this bug only occurs in MATLAB 2020a and after. Somehow, in MATLAB 2019, the "/" was ignored.
=> BEMIO read mean drift force bug fix

source/objects/ptoSimClass.m
This change allows the [PTOSim application examples](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/PTO-Sim/) to run in function and class based tests.
I am not sure if I've covered all the use cases where this change might cause an issue, but it works for me when running wecSim in the application directory (i.e. in [OSWEC_Hydraulic_PTO](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/PTO-Sim/OSWEC/OSWEC_Hydraulic_PTO)) and it now also works for the class based tests in https://github.com/WEC-Sim/WEC-Sim_Applications/pull/7
I've put this PR against master in order to get the WEC-Sim_Applications suite passing against the master branch. I am pretty sure that it will also merge into dev without issue.
=> Use the caller workspace when reading ptosim outputs

docs/_assets/gh-pages-redirect.html
Not super important as the link tag is just for SEO, but it's probably best if we fix it for correct Google results.
=> Fix link tag address in gh-pages redirect page

.gitattributes, .gitignore
This PR removes bash scripts from the top of .gitignore and .gitattributes files. Those scripts were placed there probably by a mistake.
Syntax of .gitignore and .gitattributes does not support embedding bash scripts.
This PR is ready to merge
=> Fix .gitignore and .gitattributes

tests/runFromSimTest.m
There are a few errors in the ``runFromSimTest.m`` file that results in only the Custom Parameters functionality being tested, but not Running from Simulink with an input file. This PR accurately implements new settings in the test's simulink models so that both methods of running from simulink are used.
=> Fix run from simulink test model setup

source/objects/responseClass.m
Fix for issue #724. Add a counter which is used to check whether the image is the first in order to initialize the gif file. This was originally done by check if the iteration was the first element of the time vector, but this gives an error when the wave visualization is not started at t=0.
=> Add image counter to fix gif initialization

source/functions/BEMIO/Read_CAPYTAINE.m
This fixes a bug in the BEMIO Read_Capytaine.m function. Part of that function parses dofs to ensure they are in the correct order. Capytaine always uses lower case body names when naming dofs. This PR updates Read_Capytaine to do the same and ensures the dof order is correct.
=> Bugfix for Read Capytaine

examples/BEMIO/WAMIT/RM3/bemio.m, source/functions/BEMIO/excitationIRF.m, source/functions/BEMIO/radiationIRF.m
hat tip to @crobarcro for originally implementing this improvement in RenewNet
trapz function used in B(w) cosine transformation now applied to whole arrays rather than iteratively within the k'th loop (ie over IRF time)
initial tests with RM3 show 60% reduction in RIRF computation time
=> vectorization of radiationIRF() function

docs/_templates/layout.html
Our current website analytics, Universal Analytics, is being depreciating in 2023. To begin tracking web usage we need to upgrade to Google Analytics 4. 
Google cannot convert tags automatically because this was set-up a few years ago with a format that is now outdated (``analytics.js`` instead of ``gtag.js``). Also, we don't want to remove the old analytics yet until both are working, so I cannot simply change the ID in ``conf.py``:
html_theme_options = {
'analytics_id': 'UA-XXXXXXXXXXX'
}
So, we must manually add new tags into the docs compilation process. I extended the sphinx_rtd_theme layout to include custom HTML. This will append a code block to each ``.html`` file's header that will connect pages with our new analytics stream. 
Ready for review, but leaving as a draft since this …
=> Add Google Analytics 4

examples/BEMIO/compareBEMIO.m, source/functions/BEMIO/readAQWA.m
Added a line to add a phase offset to the phase data extracted from aqwa to account for the different sign conventions used.
Thus follows from #846
=> Aqwa-phase-bug-resolved

source/functions/initializeWecSim.m, source/functions/stopWecSim.m, source/wecSimPCT.m
Fixed a few bugs, which cause WEC-Sim to crash when running wecSimPCT:
- "initializeWecSim.m": Change the project directory and move the "temp" inside the pctDir folder so that each WEC-Sim run won't interfere.
-  "stopWecSim.m": Move the command cd (['..' filesep pctDir filesep '..' filesep]); inside the "if simu.saveWorkspace==1" if loop. The command is only needed when WEC-Sim writes out the output file.
-  "wecSimPCT.m" :  Remove the pctDirs after the simulation.
=> wecSimPCT Fix (Master)

docs/user/advanced_features.rst, examples/OSWEC/wecSimInputFile.m, source/objects/bodyClass.m, tutorials/OSWEC/OSWEC_wecSimInputFile.m, tutorials/OSWEC/wecSimInputFile.m
[Project card ](https://github.com/WEC-Sim/WEC-Sim/projects/58#card-79563001)
The bodyClass fixed mass option can be somewhat misleading if there is not actually a fixed constraint. If the body isn't fixed it will likely sink indefinitely and become unphysical. Also, if a fixed constraint is connected to the body, ``body.mass='fixed'`` is not required and its mass doesn't affect the simulation.
This PR removes the ``body.mass='fixed'`` option, the associated logic, and a small related section in the documentation. For after v5.0
=> Remove fixed mass option

source/functions/BEMIO/readCAPYTAINE.m
This PR addresses issue #875. The issue has 2 parts:
1. Body name string vs. cell array formatting
- Old .nc files have body names formatted as strings while new ones have body names formatted as cell arrays
- Fix: The simple fix for this is to unpack each element of the body names.
2. Complex indices format
- Old .nc files have horizontal vectors of for specifying order of the complex dimension, while new ones have vertical vectors.
- Fix: Check whether name is a string to check version, and read in order of the complex dimension based on new vs. old version.
=> Fix readCAPYTAINE

source/objects/responseClass.m
The saveViz feature is throwing an error for elevation import because it cannot create the colorbar axis based on the wave amplitude. Since the wave amplitude is not defined for elevation import, I am changing the colorbar axis to just be based on the min and max of the wave elevation timeseries. This implementation should now work for all wave types.
=> Fixes saveViz feature for elevation import

source/functions/simulink/model/irregWaveMorison.m, source/functions/simulink/model/noWaveMorison.m, source/functions/simulink/model/regWaveMorison.m, source/objects/waveClass.m
This PR is a fix for issue #916. Because the equation for the rampFunction divides by the rampTime, it leads to an Nan value, which is not replaced by the interpolated elevation as it should be. The solution provided here checks if the rampTime is greater than 0 and applies a vector of 1s for the rampFunction if not.
=> Fix wave elevation import with rampTime = 0

source/functions/BEMIO/formatPlot.m, source/functions/BEMIO/getDofNames.m, source/functions/BEMIO/plotAddedMass.m, source/functions/BEMIO/plotBEMIO.m, source/functions/BEMIO/plotExcitationIRF.m, source/functions/BEMIO/plotExcitationMagnitude.m, source/functions/BEMIO/plotExcitationPhase.m, source/functions/BEMIO/plotRadiationDamping.m, source/functions/BEMIO/plotRadiationIRF.m, source/functions/BEMIO/readWAMIT.m
This PR enables users to input custom DOFs into ``plotBEMIO`` and the other BEMIO plotting functions (``plotAddedMass``, ``plotRadiationDamping``, etc).
This allows users to easily visualize sway, roll, yaw or GBM modes. The ``plotBEMIO`` function will use surge, heave, pitch by default if no DOF list is input. If called individually, the BEMIO plotting functions need a ``dofList`` variable defined, e.g.:
plotAddedMass([1 3 5 7],hydro,hydro,hydro)
plotAddedMass(1,hydro)
Other ways to further expand this could be enabling:
=> Customizable DOFs for plotBEMIO

examples/OSWEC/wecSimInputFile.m
This PR addresses a bug where the 'fixed' mass option was still being used for the OSWEC case, causing it to give errors when trying to run. This is only an issue in the dev branch. 
The 'fixed' mass option was removed with PR #856, but the input file to the OSWEC was changed back with [this commit](https://github.com/WEC-Sim/WEC-Sim/commit/51ef9e9322b7c08ea808263443d32092fdaa97db). This PR simply removes the 'fixed' mass and sets the mass and inertia equal to 999.
=> Remove 'fixed' mass option from OSWEC input file

source/functions/postProcessWecSim.m
This PR adds a call in ``postProcess.m`` to the pre-existing ``bodyClass.storeForceAddedMass()`` function.  This allows WEC-Sim to save the timeseries of the added mass force that is applied during the simulation. 
This is necessary for a TEAMER award where the added mass force is varied during simulation. I'd like to change a couple other items in the added mass post-processing, but this is the least intrusive and most important for visualizing the current TEAMER work.
=> Save the applied added mass time series

source/functions/simulink/model/quaternion2EulXYZ.m
An issue came up in a TEAMER award that uses two cables with spherical joints on all ends. The device motion causes the spherical joints to continuous rotate, causing an increasingly large angular position. This should be allowed to happen with a spherical joint, but our current ``quaternion2EulXYZ`` function will break if the quaternion value becomes too large. 
This PR normalizes the quaternion of any angular rotation in Simulink so that it can be robustly converted to Euler angles.
=> Normalize quaternion to increase simulation robustness

source/functions/BEMIO/readBEMIOH5.m
The roll mode rows should be 0.
The readBEMIOh5 function uses the permute command to make matrix dimensions compatible to WEC-Sim. This essentially flips the matrix, such that, $X(1:nFreq, b, a)$ becomes $X(a, b, 1:nFreq)$. This works well due to matrix symmetry. However, the roll row for linear restoration matrix must be 0.
This follows from Issue #1028
=> Fix the transpose of linear restoring matrix to make roll mode rows to be 0

README.md, docs/environment.yml
attempting to resolve https://github.com/WEC-Sim/WEC-Sim/issues/1054 by specifying the version of [sphinxcontrib-matlabdomain < 0.18.0](https://github.com/sphinx-contrib/matlabdomain)
=> Bugfix resolving documentation build error

.github/workflows/run-tests-dev.yml
This PR changes the following:
+ Added a Windows runner to the dev branch unit tests workflow by using the beta version of setup-matlab
+ Added untested versions of MATLAB (R2022a, R2022b)
+ Allows the workflow to be triggered manually
=> Add windows runner to dev branch unit test workflow

source/functions/BEMIO/readBEMIOH5.m, source/functions/BEMIO/readWAMIT.m, source/functions/BEMIO/writeBEMIOH5.m
@nathanmtom 
As mentioned in the last comment for #1063 the fix needs to be done to readWAMIT and writeBEMIOh5.
Here is an illustration.
I modified an .out file to have $(4,6)$ and $(5,6)$ terms. 
Here is how readWAMIT would read it to MATLAB workspace,
I then fixed the readWAMIT to have zeros in the $6^{th}$ row. The readWAMIT function then read the .out file correctly to the MATLAB workspace but the writeBEMIOh5 still automatically does a transpose (perhaps the writing indices are switched in the writing function),
Here is how readWAMIT read the .out file,
While after the writeBEMIOh5 is done the h5 file is written like this,
After having the trasnpose done in the writeBEMIOh5 as well, it can be seen that readWAMIT reads the matrix correctly to the workspace, and the writeBEMIOh5 writes …
=> fix_readWAMIT_and_writeBEMIOh5

source/functions/postProcessWecSim.m, source/objects/ptoSimClass.m, source/objects/responseClass.m
This PR changes the 'type' property definition for PTO-Sim blocks. Now the 'type' property is similar to the waveClass 'type' property.
This is the new 'type' property definition:
type: This property must be defined to specify the type of block that will be used. The type value of each block is presented below:
type = 'electricGen'      ---- Electric generator equivalent circuit
type = 'hydraulicCyl'     ---- Hydraulic cylinder
type = 'hydraulicAcc'     ---- Hydraulic accumulator
type = 'rectCheckValve'   ---- Rectifying check valve
type = 'hydraulicMotor'   ---- Hydraulic motor
type = 'linCrank'         ---- Linear crank 
type = 'adjustableRod'    ---- Adjustable rod 
type = 'checkValve'       ---- Check valve 
type = 'ddLinearGen'      ---- Direct drive linear generator 
type = …
=> Type property pto sim

.gitignore, examples/BEMIO/CAPYTAINE/call_capytaine.py
added a check:
- if capytaine version < 2.0, still use meshmagick to compute hydrostatics
=> use capytaine v2 to compute hydrostatics

source/objects/responseClass.m
Output order of direct drive PTO is off and leads to mix-up between electrical power and velocity.
Note: this is also likely the cause of an old issue: https://github.com/WEC-Sim/WEC-Sim/issues/1033 .
=> Fix Direct Drive PTO Output order

source/functions/initializeWecSim.m
This PR attempts to fix the error with the accelerator modes from Issue #1099. It seems to be an issue with the temp folder used to store the accelerator (MEX) files. 
This fix allows the accelerator modes to run without errors. I do not know the intended use-case of the accelerator modes though, so I find it difficult to be sure if they're working as intended.
=> Fix accelerator modes issue

docs/README.md, docs/_include/viz.rst, docs/index.rst
As I was looking at the updates to the Paraview examples for 5.11.1 (#1081), I noticed that the images weren't showing up in the docs as intended. This PR just fixes the image links.
=> Update paraview doc images

source/functions/BEMIO/readNEMOH.m
This is an update to reflect changes to the NEMOH input and output files that necessitate an update to readNEMOH. 
Changes are: 
- The NEMOH.cal allows for three options to set wave angular frequency, frequency, or period. An additional column with 1-3 to represent these three choices was added compared to last release. 
- ExcitationForce.tec has changed the name of the header from 'Diffraction force' to 'Excitation force'
The files were updated to be compatible with v3.0.0 release and existing NEMOH files in the WEC-Sim Examples BEMIO folder. 
Note: As it appears NEMOH is providing updates the WEC-Sim team may decide in the future to make readNEMOH only compatible with the latest NEMOH release.
Note: The Examples BEMIO folder need to be updated as changes to the NEMOH.cal and input.txt …
=> readNEMOH update to be compatible with v3.0.0 release (but not QTF)

.github/workflows/run-tests-dev.yml
=> Updating WEC-Sim tests for dev branch

examples/BEMIO/compareBEMIO.m
A very minor bug, part of the compareBEMIO example would break on non-windows OS due to the file seperators used. Related to a fix required in https://github.com/WEC-Sim/WEC-Sim_Applications/pull/49
=> Path fix for BEMIO example

.github/workflows/run-tests-dev.yml, .github/workflows/run-tests-master.yml
This PR is to exclude R2020b and R2021a from the Windows test runners while they seem to be broken.
Specific changes are:
+ Merged windows and linux jobs, using the matrix to vary version differences
+ Excluded R2020b and R2021a from Windows jobs
+ Include latest in the Linux jobs
EDIT: Opened bug report in `setup-matlab` [#76](https://github.com/matlab-actions/setup-matlab/issues/76).
=> Exclude R2020b and R2021a from Windows test runners

source/wecSim.m
Minor clean-up. Removes dead code from ``wecSim.m`` to prevent ``wecSimInputFile.m`` from running unnecessarily
=> Remove dead code from wecSim.m

source/functions/postProcessWecSim.m, source/wecSim.m
This PR updates wecSim.m to reference the new MoorDyn library (`libmoordyn`) instead of the old one (`Lines`). This is an update that should have been included in the previous MoorDyn updates but was left out by mistake. Discovered in Issue #1171 
This is a bug and should be pushed to both Master and Dev.
=> Update wecSim.m to new MoorDyn dll

.github/workflows/dispatch.yml, .github/workflows/docs.yml, .github/workflows/run-tests-dev.yml, .github/workflows/run-tests-master.yml
This PR ports #1186 from the dev to master branch to check if this fixes the test failures on the master branch.
+ I've also taken the opportunity to update the versions of some out-of-date actions.
+ And added R2020b and R2021a back into the windows tests now that https://github.com/matlab-actions/setup-matlab/issues/76 is resolved.
=> Port testing PR #1186 to master

source/functions/BEMIO/addDefaultPlotVars.m, source/functions/BEMIO/plotAddedMass.m, source/functions/BEMIO/plotExcitationIRF.m, source/functions/BEMIO/plotExcitationMagnitude.m, source/functions/BEMIO/plotExcitationPhase.m, source/functions/BEMIO/plotRadiationDamping.m, source/functions/BEMIO/plotRadiationIRF.m
The BEMIO plotting functions were not handling DOFs correctly when not all bodies were being input. 
e.g. ``hydro.plotBodies = 2``, then the first body was still being plotted
This PR fixes the logic in each plotting function to accurately plot the hydrodata of bodies called out in hydro.plotBodies, regardless of body order. I also updated some of the looping variables to be more meaningful so that the functions are a bit easier to follow. e.g. ``iB`` for body index, ``iDof`` for DOF index, etc
=> Bugfix for plotBEMIO bodies

source/functions/simulink/model/nonFKForce.m
This fixes pr #1220 and resolves issue #1228 by adding direction to the function call of pDis. Library link mistake caused this to update inappropriately in #1220
=> fix on pDis function call

source/functions/initializeWecSim.m, source/functions/simulink/mask/loadInputFileCallback.m, source/functions/simulink/mask/writeInputFromBlocks.m, source/functions/simulink/mask/writeLineFromVar.m
This PR fixes two bugs brought up in #1184:
=> Bug fixes for WEC-Sim GUI and Run From Simulink features

docs/conf.py, docs/environment.yml
As part of #1235, a sphinx option was incorrectly renamed from `master_doc` to `main_doc`. This PR corrects this using the `root_doc` option, available in Sphinx >= 4.
=> Fix incorrect rename of sphinx TOCtree master_doc

.github/workflows/run-tests-dev.yml, .github/workflows/run-tests-main.yml, docs/user/getting_started.rst
This PR updates the WEC-Sim tests on main and dev to only include the last 5 MATLAB releases:
- 2022a
- 2022b
- 2023a
- 2023b
- 2024a
This will officially decouple the WEC-Sim testing from the MATLAB version used to save the WEC-Sim library.
=> Updating tests on main and dev

source/functions/BEMIO/readCAPYTAINE.m
Latest version of capytaine writes hydrostatics data in the .nc file. This PR adds some code to read the hydrostatics data directly from the .nc file and removes the need to have a separate function that first writes a .dat file in python.
=> Update readCAPYTAINE.m to read Khs from .nc

source/functions/BEMIO/readCAPYTAINE.m
This is a bugfix PR to read Capytaine data when there are multiple bodies, each containing <6 DOF of hydrodynamic data
@jniffene see this one-line bugfix for our TEAMER project
=> readCapytaine - fix reading multiple bodies with <6 dofs

source/functions/BEMIO/readAQWA.m
This PR fixes 2 bugs in the readAQWA.m script to resolve #1116 :
1. The excitation phase in Ansys AQWA is given relative to the center of gravity of each body and a positive phase angle represents the excitation lagging behind the wave.
On the other hand, WEC-Sim follows WAMIT's standard, which is to define the excitation phase relative to the global origin and a positive phase angle meaning the excitation leading the wave.
The current readAQWA.m script negates the phase correctly to adjust to the discrepancy in leading/lagging, but does not take into account the difference in reference frames. Thus, WEC-Sim does not apply the correct excitation phase when using AQWA and a body is not located at the global origin. I updated the readAQWA.m script to adjust the phase of the excitation …
=> [BUG] Update readAQWA to fix excitation phase and b2b loading issues - main branch

tests/regressionTest.m
This PR expands the regression tests to account for accuracy bugs in BEMIO functions.
Currently the regression tests run the RM3 model using the committed hydroData in ``examples/RM3/hydroData/rm3.h5``.
If a BEMIO function is updated and runs functionally, but is inaccurate, the regression test will still pass because BEMIO is not being re-run. e.g. the tests [here](https://github.com/WEC-Sim/WEC-Sim/pull/1263/checks?check_run_id=27383027089) should have failed because the body cg, cb and volume were written incorrectly. The regression tests passed however because BEMIO is not rerun.
This update will _not_ catch inaccuracies in:
- readCAPYTAINE
- readNEMOH
- readAQWA
but it will catch issues in readWAMIT, radiationIRF, radiationIRFSS, excitationIRF, and writeBEMIOH5
=> Expand regression tests

source/functions/BEMIO/writeBEMIOH5.m
``writeBEMIOH5`` can take a very long time. Almost all of the BEM coefficients are written twice, in the "components" groups, but never used in WEC-Sim. These groups are never read in by ``readBEMIOH5``
In my testing with the [directional OSWEC data in the Applications repo](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/main/_Common_Input_Files/OSWEC/hydroData), this duplicate data takes approximately 98.9% of the CPU time of ``writeBEMIOH5`` and increases the H5 file size by almost 4 times.
This PR eliminates the duplicate writing of BEM data into the "component" groups and significantly reduces the computational expense of ``writeBEMIOH5``. This will critically enable the use of variable hydro.
=> Speed up writeBEMIOH5

source/objects/ptoSimClass.m
This PR is related to issue #1314 
The comments for the PTO-Sim class have been revised and updated
=> Fixing documentation inconsistency for PTO-Sim blocks

docs/conf.py, docs/environment.yml
This PR updates the Google analytics implementation in our docs per the deprecation of ``analytics_id``. See example of failing docs build [here](https://github.com/WEC-Sim/WEC-Sim/actions/runs/11368439659/job/31623533133?pr=1340). Per that deprecation warning, I utilize [sphinxcontrib.googleanalytics](https://pypi.org/project/sphinxcontrib-googleanalytics/) in the build environment
=> Update Google analytics implementation in docs 

source/functions/BEMIO/readWAMIT.m
This PR resolves #1305. No other BEMIO functions gave this indexing error except readWAMIT.
=> Resolve issue #1305 - MATLAB deprecation warning in readWAMIT

source/functions/initializeWecSim.m, source/functions/postProcessWecSim.m, source/objects/mooringClass.m, source/objects/responseClass.m
This PR fixes some MoorDyn path things to support V2 (input files can have any name or path). Previously there were instances of MoorDyn v1 file naming that was hard coded. Now, the input file name and path is used to derive the output file names and paths. This requires the MoorDyn filename in the wecSimInputFile to only have a single "." character, I added tests accordingly that check this and that the file exists. 
If there are formatting things that need changing here please let me know! I tried to follow how other parts of the code do things as closely as possible.
=> MoorDyn variable path support

.github/workflows/run-tests-dev.yml, .github/workflows/run-tests-main.yml
Updates the Matlab and the Ubuntu versions in the workflow.
Limits the tests to ubuntu-22.04 rather than ubuntu-latest (ubuntu-24.04). Only Matlab 2024x is compatible with ubuntu-24.04.
Noting that the Ubuntu 20.04 runner image will be fully unsupported by github on April 1, 2025
=> Updates the Ubuntu and Matlab versions

.github/workflows/run-tests-dev.yml, .github/workflows/run-tests-main.yml, source/objects/waveClass.m
This PR fixes the irregular wave elevation function, which was failing for multiple directions. This was causing the [Morison Element applications case to fail](https://github.com/WEC-Sim/WEC-Sim_Applications/actions/runs/12776912600/job/36069012775) - see #1400. The OSWEC case was also erroring because it had multiple wave directions.
@dforbush2 I traced this change back to our PR #1332, but I don't think it was intentional since you created a new function `waves.waveElevFullDir()` for the imported full directional wave elevation.
=> Fix irregular wave elevation with multiple directions

docs/user/advanced_features.rst, source/functions/BEMIO/readH5ToStruct.m, source/functions/BEMIO/rebuildHydroStruct.m, source/functions/initializeWecSim.m, source/objects/bodyClass.m
I know this is already possible using the multiple run condition work flow, but for my work flow that process seemed inconvenient and not very intuitive. See discussion #1410 for more background.
This PR has a small edit to the BodyClass constructor, allowing for either an h5File to be the input (so the old workflow shouldn't be disrupted), or a structure. I've included a quick check on the structure format (mostly just to make sure the structure that BEMIO uses for writing the h5file isn't mistakenly being used) but it might be worth it to add a more robust check.
Additionally I made an edit to the initializeWecSim script to make use of the new capability this constructor enables.
Let me know if you think adding a more detailed check on the structure is worthwhile and if any additional …
=> build Body from hydro structure directly

source/functions/paraview/paraviewVisualization.m
This PR addresses #1438 which found a bug in the paraview output function. If `simu.paraview.dt` is larger than `simu.dt`, the paraview timestep will only be applied to the first body. To fix this, I moved the if statement to before the bodies are looped through and moved the time vector selection outside of the if statement so it is applied for all bodies.
Thanks for finding this issue and suggesting a fix @hamzaJayy.
=> Fix paraview output function

source/objects/waveClass.m
This PR updates the random number generation in `setWavePhase` in the `waveClass` to use `RandStream` with `Substream`, instead of `rng(phaseSeed)`. The change ensures deterministic and reproducible wave elevation profiles across both serial (`wecSim`) and parallel (`wecSimPCT`) simulations when `phaseSeed` is specified. This resolves the issue where parallel runs with the same seed could produce different results due to independent worker streams (see Issue #1329 ). The new approach uses the `Threefry` generator, which supports substreams and is recommended by MathWorks for parallel reproducibility.
This PR can be tested using the MCR example available here: WEC-Sim_Applications/Multiple_Condition_Runs/RM3_MCROPT3 running the attached script. …
=> Fix wave generation with phaseSeed in waveClass for PCT

source/objects/cableClass.m
@MShabara I did modify the cableClass.m to correct a cable pretension calculation. This modification is only for the cable tension input whereas the cable length input was good to calculate the cable tension output.
=> Modified sign convention when a cable pretension is defined

docs/_include/variable_hydro.rst, docs/user/applications.rst, source/objects/bodyClass.m
This PR updates the variable mass to follow the workflow:
1. Use variable mass inputs from user.
2. If no variable mass input but variable inertia is present in the input file, assume equilibrium and use the provided variable inertia.
3. If no variable mass or inertia is present, use the specified body mass and inertia for all variable hydro cases.
I also added some documentation for the updated variable mass example ([PR 90 on Applications](https://github.com/WEC-Sim/WEC-Sim_Applications/pull/90)).
=> Update variable mass implementation and add documentation

docs/theory/theory.rst, source/functions/BEMIO/badBemioFix_fcn.m, source/functions/BEMIO/cleanBEM.m, source/functions/BEMIO/radiationIRF.m
This PR refactors `badBemioFix_fcn`:
- renames function to `cleanBEM`
- modularizes - the peak smoothing is turned into a single function that is used for all hydro coefficients (A, B, Fex).
- simplifies the interpolation to use the built-in `interp1` for consistency and ease of changing the interpolation method
- aligns the usage of the function with the rest of BEMIO
- This is now a standalone function that can be called with any pre-existing hydro structure and it does not read in coefficients on its own
- IRF and SS coefficients are removed and must be recreated after using this function to fix A, B, Fex
- IRF and SS function calls are not repeated within the cleaning function, saving time
- reorganizes the despike structure to fit the function-based method within `cleanBEM`
and fixes …
=> Refactor badBemioFix_fcn

source/objects/+internal/waveType.m, source/objects/waveClass.m
Improves the `waveClass` constructor by replacing string-based type validation with a MATLAB enumeration. This implementation suggests the different wave types to users as they construct `waveClass` objects, and reduces boilerplate code.
- **Modified**: `source/objects/waveClass.m` - Updated constructor to use `arguments` block with `internal.waveType` validation
- **Added**: `source/objects/+internal/waveType.m` - New enumeration defining all valid wave types
- **Type Safety**: Compile-time validation prevents invalid wave type strings
- **Better IntelliSense**: IDE can provide autocomplete for valid wave types  
- **Future-proof**: Easy to add new wave types by extending the enumeration
- **Backward Compatible**: Existing functionality unchanged
=> `waveClass` Constructor Improvements

source/functions/simulink/model/nonFKForce.m
This PR fixes the nonlinear hydro calculation for cases with wave spreading. The spread term is moved to under the square root to be consistent with our [documentation](https://wec-sim.github.io/WEC-Sim/main/theory/theory.html#frequency-varying-direction-and-spread) and the other irregular excitation functions. 
I tested this to make sure everything runs, but I did not get a chance to test a nonlinear case with spread. A quick test would be to run the OSWEC case with nonlinear hydrodynamics and an irregular wave with spread in a few directions. Then, compare the result to the same irregular wave without spread. The result should show increased excitation for the case without spread (difference depends on the spread values).
=> Fix spread with nonlinear hydro
