WEC-Sim/WEC-Sim

- source/functions/moorDyn/LICENSE.txt
- source/functions/moorDyn/readme.txt
- providing 64-bit Windows DLL for v1.00.04C
- (dylib will still need to be compiled by someone else)
- added short copyright/licensing/information text file
- added license text file
> MoorDyn update (v1.00.04C) and license notice added

- source/lib/WEC-Sim/WECSim_Lib.mdl
- source/objects/bodyClass.m
- source/objects/waveClass.m
Changes of the linear wave excitation force in the MATLAB function of the Wec-Sim model to account the wave directions. Including the reading of the hydrodynamic excitation coefficients for all the directions of the hydrodata file in bodyclass. Including a wave spread and random phase generation for all the wave directions.
> Directional waves

- source/wecSim.m
For details, check issue https://github.com/WEC-Sim/WEC-Sim/issues/277
> Store Simulink data in the "parent" workspace of MATLAB

- source/objects/waveClass.m
This pull request is for a small change to improve the help for currentOption and currentDepth properties in waveSettings.m
> waveClass.m: change of formatting for help text

- source/objects/bodyClass.m
- source/objects/responseClass.m
- source/objects/waveClass.m
Hello,
I've replaced all offending Integars in the API documentation.
> Replaced 'Integar' with Integer

- source/objects/simulationClass.m
- source/wecSim.m
This includes the update saving wec-sim output to a structure instead of an object.
> merging updates to master into dev

- source/objects/simulationClass.m
- source/wecSim.m
This merge makes the default WEC-Sim output a structure and suppressing the MATLAB warning.
> merging master into dev

- source/objects/waveClass.m
Update the calculation of the power contained within an irregular wave spectrum. There was a factor of 2\pi off in the calculation.
> Update waveClass in reference to issue #564

- source/functions/BEMIO/Radiation_IRF_SS.m
- source/functions/BEMIO/Read_CAPYTAINE.m
There's a bug in the Read_CAPYTAINE BEMIO function that doesn't allow <6 DOFs.
This PR fixes this problem and solves issue #599.
> Bugfix read capytaine

- docs/_include/viz.rst
- docs/man/advanced_features.rst
This PR relates to https://github.com/WEC-Sim/WEC-Sim/pull/595 and updates the documentation for using ParaView to visualize WEC-Sim data. Merging into master since it's related to a bug-fox.
> Updating ParaView Doc

- .github/workflows/run-tests-dev.yml
- .github/workflows/run-tests-example.yml
- .github/workflows/run-tests-master.yml
- tests/bemioTest.m
- tests/runFromSimTest.m
* Adds a testing workflow for the master and dev branches
* Fixes issue with windows specific paths in bemio tests
> Setup GitHub Actions

- examples/OSWEC/wecSimInputFile.m
- examples/RM3/userDefinedFunctions.m
- source/objects/responseClass.m
This PR resolves the issue #693 .
This is done by adding an if statement that ensures the initial angular position is NOT subtracted from the angular mode responses.
> Remove Bias from Angular mode reponses resolves issue #693

- source/functions/postProcessWecSim.m
- source/objects/ptoSimClass.m
- source/objects/responseClass.m
- source/objects/simulationClass.m
This PR primarily updates the response class API to
> Update response class API

- examples/RM3/userDefinedFunctions.m
- examples/RM3/wecSimInputFile.m
- source/functions/initializeWecSim.m
- source/objects/bodyClass.m
- source/objects/cableClass.m
- source/objects/constraintClass.m
- source/objects/mooringClass.m
- source/objects/ptoClass.m
- source/objects/ptoSimClass.m
- source/objects/responseClass.m
- source/objects/simulationClass.m
- source/objects/waveClass.m
- source/wecSim.m
Reverts WEC-Sim/WEC-Sim#820
This was a mistake -- I was trying to pull dev into my branch and it pulled my branch into dev instead
> Revert "DRAFT: Warning/Error flags"

- .github/workflows/docs.yml
- docs/README.md
- docs/_include/viz.rst
- docs/conf.py
This is a test PR to check if making errors in the docs results in a build fail at this stage. Presently it does not, which is not the desired behaviour.
Fixes #835
> Add branch build in docs workflow for testing PRs

- .github/workflows/docs.yml
- .gitignore
- docs/README.md
- docs/conf.py
- source/functions/initializeWecSim.m
- source/functions/stopWecSim.m
- source/objects/waveClass.m
- source/wecSim.m
- source/wecSimPCT.m
making sure dev includes everything from master
> Pulling master into dev

- source/objects/responseClass.m
This PR is in reference to Issue #864 and updates the saveViz feature to work with the v5.0 release.
> Fix saveViz

- source/functions/BEMIO/readCAPYTAINE.m
- source/functions/simulink/model/irregWaveMorison.m
- source/functions/simulink/model/noWaveMorison.m
- source/functions/simulink/model/regWaveMorison.m
- source/objects/responseClass.m
- source/objects/waveClass.m
This PR pulls 3 dev-branch bugfixes into master (#929 #917 #884)
will merge once checks run
> Pull dev bugfixes into master

- docs/index.rst
- docs/introduction/release_notes.rst
This PR updates Sal's name in the citation, per his request. 
@salhus Anything I missed here? I'll pull this into dev once it is merged.
Adam
> Update citation names

- docs/index.rst
- docs/introduction/release_notes.rst
> Pull #954 into dev

- source/functions/simulink/model/nonLinearBuoyancy.m
This reverts commit 118f1566a326ecfe24d6abf398792d44c1760b61.
> Revert "fix non-linear hydro (#910)"

- source/functions/BEMIO/readNEMOH.m
This PR is for pushing the changes made in PR #1087 into the WEC-Sim Master Branch.
> Update readNEMOH.m for compatibility with NEMOH v3.0

- .github/workflows/run-tests-dev.yml
- .github/workflows/run-tests-master.yml
- docs/_assets/gh-pages-redirect.html
- docs/environment.yml
- docs/introduction/release_notes.rst
- docs/most/release_notes.rst
> updating v6.0 release notes

- .github/workflows/dispatch.yml
- .github/workflows/docs.yml
- .github/workflows/run-tests-dev.yml
- .github/workflows/run-tests-master.yml
This PR includes R2023b in both the Linux and Windows test suites.
+ I've also taken the opportunity to update the versions of some out-of-date actions.
+ And added R2020b and R2021a back into the windows tests now that https://github.com/matlab-actions/setup-matlab/issues/76 is resolved.
> Add R2023b to Windows tests

- docs/_include/viz.rst
This PR fixes a small bug in the documentation to resolve #1225.
> Update paraview docs

- docs/_include/added_mass.rst
This PR contains a couple minor formatting fixes for the added mass section of the developer manual.
> Minor fix for formatting in Developer manual

- source/functions/BEMIO/readAQWA.m
Pulling readAQWA updates into dev
> Update readAQWA.m (#1253)

- source/functions/initializeWecSim.m
> Revert "Full directional spectra implementation"

- docs/conf.py
- docs/environment.yml
- source/objects/ptoSimClass.m
* Fixing documentation inconsistency for PTO-Sim blocks
* Adding comments to nondimensional values for clarification
> Fixing documentation inconsistency for PTO-Sim blocks (#1330)

- source/functions/BEMIO/QTFs/plotQTFs.m
- source/functions/BEMIO/QTFs/triToFullMatrix.m
Unifies the mod naming across BIMIO to be `MOD_F_ij` instead of `MOD_ij`
> Minor bug fix related to PR #1353

- source/objects/waveClass.m
Refer to https://github.com/WEC-Sim/WEC-Sim/issues/1356 for details. I made a minor update to the waveClass to resolve the unit discrepancy.
> Resolve unit discrepancy from #1356

- source/functions/initializeWecSim.m
Bug fix to dev so that we only check the mooring file path when using MoorDyn.
> Fix mooring path check

- docs/index.rst
- docs/introduction/release_notes.rst
- docs/user/advanced_features.rst
- source/functions/simulink/model/secondOrderExt.m
- source/objects/simulationClass.m
- source/wecSimPCT.m
> KeepParallelPool

- docs/_include/added_mass.rst
Pull bug fixes (#1425) from main into dev
> Pull bug fixes from main into dev

- docs/_include/mooring.rst
- source/functions/paraview/WEC-Sim.py
- source/functions/paraview/paraviewVisualization.m
- source/functions/paraview/writeParaviewMooring.m
- source/functions/paraview/writeParaviewResponse.m
- source/functions/paraview/writeParaviewWave.m
- source/functions/postProcessWecSim.m
- source/objects/responseClass.m
New PR, building on https://github.com/WEC-Sim/WEC-Sim/pull/1441, focused on MoorDyn to ParView for multiple mooring connections
> ParaView feature for multiple mooring connections #1440
